### ISSUE TITLE
Error when creating  new project

### ISSUE THREAD

**Issue by sebastienblanc** [forge/springboot-addon#4]
I'm getting an exception at the last step of creating a new project of Spring Boot type : 
```
java.lang.NoClassDefFoundError: org/jboss/forge/addon/maven/archetype/ArchetypeHelper
	at org.jboss.forge.addon.springboot.commands.setup.SetupProjectCommand.execute(SetupProjectCommand.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.springboot.commands.setup.SetupProjectCommand_$$_javassist_257440e5-3173-4b80-8e18-738615ec735f.execute(SetupProjectCommand_$$_javassist_257440e5-3173-4b80-8e18-738615ec735f.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_8b3bf9df-7f1f-4c00-a0cd-5affb3a115d1.execute(CommandController_$$_javassist_8b3bf9df-7f1f-4c00-a0cd-5affb3a115d1.java)
	at org.jboss.tools.forge.ui.internal.ext.wizards.ForgeWizard$1.run(ForgeWizard.java:113)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.ClassNotFoundException: org.jboss.forge.addon.maven.archetype.ArchetypeHelper from [Module
```

**Comment by gastaldi** [comment]
What Forge version are you using? This change was introduced since 3.5.1.Final afaik

**Comment by sebastienblanc** [comment]
Ah okay ,  I'm still on an "old" 3.4.0 ;)

**Comment by cmoulliard** [comment]
I will add a comment within the doc page to mention that Forge >= 3.5 is required.

**Comment by cmoulliard** [comment]
Can we close the ticket @sebastienblanc ?
